import requests
import logging

logger = logging.getLogger(__name__)

def is_valid_link(url: str, timeout: int = 10) -> bool:
    """
    Performs a strict HTTP check to verify the link returns a valid 200/300-level response.
    Returns False if it encounters a 403, 404, Captcha block, or connection error.
    """
    if not url or url.startswith('http://localhost') or url.startswith('http://127.0.0.1'):
        return False
        
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.5",
    }
    
    try:
        # Use a GET request because some CDNs block HEAD requests
        response = requests.get(url, headers=headers, timeout=timeout, allow_redirects=True, stream=True)
        # Only read a small chunk to save bandwidth
        content = next(response.iter_content(chunk_size=1024), b"").decode('utf-8', errors='ignore')
        response.close()
        
        # Check HTTP status code
        if response.status_code >= 400:
            logger.warning(f"URL Validation Failed: {url} returned HTTP {response.status_code}")
            return False
            
        # Check for common WAF / anti-bot challenge pages that return 200 OK
        challenge_markers = [
            "Generated by cloudfront",
            "Request blocked",
            "Access Restricted",
            "recaptcha/api.js",
            "cloudflare",
            "Incapsula",
            "Please verify you are a human"
        ]
        
        for marker in challenge_markers:
            if marker.lower() in content.lower():
                logger.warning(f"URL Validation Failed: {url} returned a Captcha/WAF block page.")
                return False
                
        return True
    except requests.RequestException as e:
        logger.warning(f"URL Validation Failed: {url} raised exception {e}")
        return False
